title: Le blog de DossierSCO
email: equipe@dossiersco.fr
description: >- # this means to ignore newlines until "baseurl:"
  Toute l'actualité de DossierSCO, le service public numérique de l'Education Nationale pour faciliter l'inscription au collège.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dossiersco

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
sass:
  sass_dir: _sass
  style: compressed
show_excerpts: true
